name: GoMinute
favicon: null
layout_spectrum: 0.7753232934046537
typography_spectrum: 0.42028981330804527
title: Slow Down Eating for Better Health
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.14037178573198617
  lightness: 0.017813691403716803
  saturation: 0.42658389336429536
  rhythmicContrast: 0.804594396147877
purpose: []
